[theme]

# Primary accent for interactive elements
primaryColor = '#008080'

# Background color for the main content area
backgroundColor = '#E4FDF6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ACC9C4'

# Color used for almost all text
textColor = '#161616'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
